# Employee Data Analysis with pandas

This portfolio project uses a small employee dataset to demonstrate practical data analysis with pandas. The analysis focuses on salary, department, employment type, and years of experience.

## Skills Demonstrated

- Creating and exploring a pandas DataFrame
- Grouping data with `groupby()`
- Calculating summary statistics
- Aggregating multiple measures
- Comparing categories within a dataset
- Interpreting analysis results

> **Note:** This notebook is a portfolio adaptation of coursework completed while learning pandas.

In [1]:
import pandas as pd

## Employee Dataset

The dataset contains 10 employees across Administration, Marketing, and Technical departments, with information about employment type, salary, and years of experience.

In [2]:
data_df = {
    'Name': ['Asha', 'Harsh', 'Sourav', 'Riya', 'Hritik',
             'Shivansh', 'Rohan', 'Akash', 'Soumya', 'Kartik'],

    'Department': ['Administration', 'Marketing', 'Technical', 'Technical', 'Marketing',
                   'Administration', 'Technical', 'Marketing', 'Technical', 'Administration'],

    'Employment Type': ['Full-time Employee', 'Intern', 'Intern', 'Part-time Employee',
                        'Part-time Employee', 'Full-time Employee', 'Full-time Employee',
                        'Intern', 'Intern', 'Full-time Employee'],

    'Salary': [120000, 50000, 70000, 70000, 55000,
               120000, 125000, 60000, 50000, 120000],

    'Years of Experience': [5, 1, 2, 3, 4, 7, 6, 2, 1, 6]
}

mlp = pd.DataFrame(data_df)
mlp

       Name      Department     Employment Type  Salary  Years of Experience
0      Asha  Administration  Full-time Employee  120000                    5
1     Harsh       Marketing              Intern   50000                    1
2    Sourav       Technical              Intern   70000                    2
3      Riya       Technical  Part-time Employee   70000                    3
4    Hritik       Marketing  Part-time Employee   55000                    4
5  Shivansh  Administration  Full-time Employee  120000                    7
6     Rohan       Technical  Full-time Employee  125000                    6
7     Akash       Marketing              Intern   60000                    2
8    Soumya       Technical              Intern   50000                    1
9    Kartik  Administration  Full-time Employee  120000                    6

## Average Experience by Department

This analysis calculates the average years of experience for employees in each department.

In [3]:
mlp.groupby('Department')['Years of Experience'].mean()

Department
Administration    6.000000
Marketing         2.333333
Technical         3.000000
Name: Years of Experience, dtype: float64

### Key Finding

Administration has the highest average experience at 6 years, while Marketing has the lowest at approximately 2.3 years.

## Maximum Salary by Department

This analysis identifies the highest salary within each department.

In [4]:
mlp.groupby('Department')['Salary'].max()

Department
Administration    120000
Marketing          60000
Technical         125000
Name: Salary, dtype: int64

### Key Finding

The Technical department has the highest maximum salary in the dataset at $125,000.

## Salary and Experience by Department

This analysis compares the minimum, average, and maximum salary and years of experience across departments.

In [5]:
mlp.groupby('Department')[['Salary', 'Years of Experience']].agg(['min', 'mean', 'max'])

                Salary                   Years of Experience
                   min      mean     max                 min      mean max
Department
Administration  120000  120000.0  120000                   5  6.000000   7
Marketing        50000   55000.0   60000                   1  2.333333   4
Technical        50000   78750.0  125000                   1  3.000000   6

### Key Findings

- Administration has a consistent salary of $120,000 across the employees in this dataset.
- Technical salaries range from $50,000 to $125,000, the widest range among the departments.
- Marketing has the lowest average years of experience at approximately 2.3 years.
- Administration has the highest average years of experience at 6 years.

## Average Salary by Department and Employment Type

Grouping by both department and employment type allows a more detailed comparison of salaries within each department.

In [6]:
mlp.groupby(['Department', 'Employment Type'])['Salary'].mean()

Department      Employment Type
Administration  Full-time Employee    120000.0
Marketing       Intern                 55000.0
                Part-time Employee     55000.0
Technical       Full-time Employee    125000.0
                Intern                 60000.0
                Part-time Employee     70000.0
Name: Salary, dtype: float64

### Key Finding

Within the Technical department, interns have an average salary of $60,000 in this dataset. Grouping by multiple categories makes it easier to compare compensation across both department and employment type.

## Summary

This analysis demonstrates how pandas can be used to organize employee data, calculate grouped statistics, and compare patterns across departments and employment types. These techniques are useful for exploratory data analysis and for turning structured data into clear, interpretable insights.